#!/bin/sh -e
# releases a new tarball (still needs linking) to blog

TARGET='/var/www/www.pitt-pladdy.com-blogdata/20091122-164951_0000_Postfix_stats_on_Cacti_via_SNMP_'

# get our workspace sorted
workingdir=`mktemp --directory -t cacti-uloganalyser_release-postfix.XXXXXXXXXX`

# datestamp
datestamp=`date +%Y%m%d`
datedir="$workingdir/$datestamp"
mkdir "$datedir"

# populate
cp postfix/postfix* postfix/cacti_host_template_postfix.xml "$datedir/"
cp postfix/clamav* postfix/cacti_graph_template_clamav.xml "$datedir/"
cp postfix/dkim* postfix/cacti_graph_template_dkim-filter.xml "$datedir/"
cp postfix/spamd* postfix/cacti_host_template_spamd_monitoring.xml "$datedir/"

# tarball
cd "$workingdir/"
tar jcvf "postfix_cacti-$datestamp.tar.bz2" "$datestamp/"
mv -i "postfix_cacti-$datestamp.tar.bz2" "$TARGET"

# clean up
rm -r "$workingdir"

# announce
echo "Don't forget to edit in new release: https://www.pitt-pladdy.com/seatofpower/blog/_20091122-164951_0000_Postfix_stats_on_Cacti_via_SNMP_/"


