#!/bin/sh

# make up dummy logs
./testdata2tmp >/tmp/testlog
touch /tmp/testlog.0
./testdata2tmp testdoveadm/\* >/tmp/testdoveadm

# run uloganalyser against them
rm /tmp/ustat
./uloganalyser /tmp/testlog.0 /tmp/testlog \
	/tmp/ustat */*.pm

# diff if we got files
if [ -f /tmp/ustat -a -f ustat.last ]; then
	echo "============= diff"
	diff -u ustat.last /tmp/ustat
fi

