#!/bin/sh
# Copyright (C) 2012  Glen Pitt-Pladdy
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# See: https://www.pitt-pladdy.com/blog/_20130324-154457_0000_fail2ban_on_Cacti_via_SNMP/


PATH=/bin:/usr/bin
STATS=/var/local/snmp/fail2ban


printf "%d\n" `grep ^fail2ban:banned:other= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^fail2ban:banned:mail= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^fail2ban:banned:ssh= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^fail2ban:banned:www= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^fail2ban:banned:dns= $STATS | cut -d '=' -f2`
