#!/bin/sh
# Copyright (C) 2011  Glen Pitt-Pladdy
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# See: http://www.pitt-pladdy.com/


PATH=/bin:/usr/bin
STATS=/var/local/snmp/mail


printf "%d\n" `grep ^dovecot:imap:login= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:imap:login:other= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:imap:login:success= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:imap:login:disconnected= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:imap:login:disconnected:other= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:imap:login:disconnected:noauthattempt= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:imap:login:disconnected:authfailed= $STATS | cut -d '=' -f2`
