#!/bin/sh
# Copyright (C) 2011  Glen Pitt-Pladdy
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# See: http://www.pitt-pladdy.com/blog/_20110625-123333%2B0100%20Dovecot%20stats%20on%20Cacti%20%28via%20SNMP%29/


PATH=/bin:/usr/bin
STATS=/var/local/snmp/mail


printf "%d\n" `grep ^dovecot:pop3:loginmethod:other= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:loginmethod:plain= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:loginmethod:login= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:loginmethod:crammd5= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:loginmethod:digestmd5= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:loginmethod:apop= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:loginmethod:ntlm= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:loginmethod:gssspnego= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:loginmethod:gssapi= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:loginmethod:rpa= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:loginmethod:anonymous= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:loginmethod:otp= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:loginmethod:skey= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:loginmethod:external= $STATS | cut -d '=' -f2`
