#!/bin/sh
# Copyright (C) 2011  Glen Pitt-Pladdy
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# See: https://www.pitt-pladdy.com/blog/_20110625-123333%2B0100%20Dovecot%20stats%20on%20Cacti%20%28via%20SNMP%29/


PATH=/bin:/usr/bin
STATS=/var/local/snmp/mail


printf "%d\n" `grep ^dovecot:pop3:login= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:other= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:success= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:disconnected= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:disconnected:other= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:disconnected:noauthattempt= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:disconnected:authfailed= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:aborted= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:aborted:other= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:aborted:noauthattempt= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:aborted:authfailed= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:maxconnections= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:disconnected:authenticating= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:aborted:disabledauthmethod= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:disconnected:disabledauthmethod= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:disconnected:beforegreeting= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:disconnected:proxybyserver= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^dovecot:pop3:login:disconnected:proxybyclient= $STATS | cut -d '=' -f2`
