#!/bin/sh
# Copyright (C) 2009  Glen Pitt-Pladdy
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# See: https://www.pitt-pladdy.com/blog/_20091122-164951%2B0000%20Postfix%20stats%20on%20Cacti%20%28via%20SNMP%29/


PATH=/bin:/usr/bin
STATS=/var/local/snmp/mail


printf "%d\n" `grep ^clamav:other= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^clamav:found= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^clamav:found:trojan= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^clamav:found:phishing= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^clamav:found:fraud= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^clamav:found:scam= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^clamav:found:exploit= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^clamav:found:virus= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^clamav:found:worm= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^clamav:found:malware= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^clamav:found:spam= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^clamav:found:archive= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^clamav:found:suspect= $STATS | cut -d '=' -f2`
