#!/bin/sh
# Copyright (C) 2014  Glen Pitt-Pladdy
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# See: https://www.pitt-pladdy.com/blog/_20150213-225132_0000_opendkim_on_Cacti_via_SNMP/


PATH=/bin:/usr/bin
STATS=/var/local/snmp/mail


printf "%d\n" `grep ^opendkim:other= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^opendkim:addedsignature= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^opendkim:nosignature= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^opendkim:verifysuccess= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^opendkim:badsignature= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^opendkim:keyretrievalfail= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^opendkim:badsignaturedata= $STATS | cut -d '=' -f2`
# TODO printf "%d\n" `grep ^opendkim:badheader= $STATS | cut -d '=' -f2`

