#!/bin/sh
# Copyright (C) 2009  Glen Pitt-Pladdy
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# See: https://www.pitt-pladdy.com/blog/_20091122-164951%2B0000%20Postfix%20stats%20on%20Cacti%20%28via%20SNMP%29/


PATH=/bin:/usr/bin
STATS=/var/local/snmp/mail


# currently smtp:TLS is unused, but here for completeness
printf "%d\n" `grep ^postfix:smtp:TLS= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^postfix:smtp:TLS:Trusted= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^postfix:smtp:TLS:Untrusted= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^postfix:smtp:TLS:Anonymous= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^postfix:smtp:TLS:Verified= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^postfix:smtp:TLS:certverifyfail= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^postfix:smtp:TLS:certverifyfail:other= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^postfix:smtp:TLS:certverifyfail:selfsigned= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^postfix:smtp:TLS:certverifyfail:untrusted= $STATS | cut -d '=' -f2`
printf "%d\n" `grep ^postfix:smtp:TLS:certverifyfail:expired= $STATS | cut -d '=' -f2`
